//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2.SuperStoreServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrationContainer", Namespace="http://schemas.datacontract.org/2004/07/SuperStoreLibrary.Communication")]
    [System.SerializableAttribute()]
    public partial class RegistrationContainer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationCredentials", Namespace="http://schemas.datacontract.org/2004/07/SuperStoreLibrary.Communication")]
    [System.SerializableAttribute()]
    public partial class AuthenticationCredentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerContainer", Namespace="http://schemas.datacontract.org/2004/07/SuperStoreLibrary.Communication")]
    [System.SerializableAttribute()]
    public partial class CustomerContainer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfApplication2.SuperStoreServiceReference.AuthenticationCredentials credentialsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double saldoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfApplication2.SuperStoreServiceReference.AuthenticationCredentials credentials {
            get {
                return this.credentialsField;
            }
            set {
                if ((object.ReferenceEquals(this.credentialsField, value) != true)) {
                    this.credentialsField = value;
                    this.RaisePropertyChanged("credentials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double saldo {
            get {
                return this.saldoField;
            }
            set {
                if ((this.saldoField.Equals(value) != true)) {
                    this.saldoField = value;
                    this.RaisePropertyChanged("saldo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pagination", Namespace="http://schemas.datacontract.org/2004/07/SuperStoreLibrary.Communication")]
    [System.SerializableAttribute()]
    public partial class Pagination : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                if ((this.pageIndexField.Equals(value) != true)) {
                    this.pageIndexField = value;
                    this.RaisePropertyChanged("pageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                if ((this.pageSizeField.Equals(value) != true)) {
                    this.pageSizeField = value;
                    this.RaisePropertyChanged("pageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductResponseContainer", Namespace="http://schemas.datacontract.org/2004/07/SuperStoreLibrary.Communication")]
    [System.SerializableAttribute()]
    public partial class ProductResponseContainer : WpfApplication2.SuperStoreServiceReference.ProductRequestContainer {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stockField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                if ((this.stockField.Equals(value) != true)) {
                    this.stockField = value;
                    this.RaisePropertyChanged("stock");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductRequestContainer", Namespace="http://schemas.datacontract.org/2004/07/SuperStoreLibrary.Communication")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfApplication2.SuperStoreServiceReference.ProductResponseContainer))]
    public partial class ProductRequestContainer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseResponseContainer", Namespace="http://schemas.datacontract.org/2004/07/SuperStoreLibrary.Communication")]
    [System.SerializableAttribute()]
    public partial class PurchaseResponseContainer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfApplication2.SuperStoreServiceReference.ProductResponseContainer productField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfApplication2.SuperStoreServiceReference.ProductResponseContainer product {
            get {
                return this.productField;
            }
            set {
                if ((object.ReferenceEquals(this.productField, value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseRequestContainer", Namespace="http://schemas.datacontract.org/2004/07/SuperStoreLibrary.Communication")]
    [System.SerializableAttribute()]
    public partial class PurchaseRequestContainer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfApplication2.SuperStoreServiceReference.ProductRequestContainer productField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfApplication2.SuperStoreServiceReference.ProductRequestContainer product {
            get {
                return this.productField;
            }
            set {
                if ((object.ReferenceEquals(this.productField, value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SuperStoreServiceReference.SuperStoreServiceInterface")]
    public interface SuperStoreServiceInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuperStoreServiceInterface/RegisterNewUser", ReplyAction="http://tempuri.org/SuperStoreServiceInterface/RegisterNewUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/SuperStoreServiceInterface/RegisterNewUserFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        WpfApplication2.SuperStoreServiceReference.AuthenticationCredentials RegisterNewUser(WpfApplication2.SuperStoreServiceReference.RegistrationContainer userDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuperStoreServiceInterface/RegisterNewUser", ReplyAction="http://tempuri.org/SuperStoreServiceInterface/RegisterNewUserResponse")]
        System.Threading.Tasks.Task<WpfApplication2.SuperStoreServiceReference.AuthenticationCredentials> RegisterNewUserAsync(WpfApplication2.SuperStoreServiceReference.RegistrationContainer userDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuperStoreServiceInterface/RetrieveUserInfo", ReplyAction="http://tempuri.org/SuperStoreServiceInterface/RetrieveUserInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/SuperStoreServiceInterface/RetrieveUserInfoFaultExceptionFault" +
            "", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        WpfApplication2.SuperStoreServiceReference.CustomerContainer RetrieveUserInfo(WpfApplication2.SuperStoreServiceReference.AuthenticationCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuperStoreServiceInterface/RetrieveUserInfo", ReplyAction="http://tempuri.org/SuperStoreServiceInterface/RetrieveUserInfoResponse")]
        System.Threading.Tasks.Task<WpfApplication2.SuperStoreServiceReference.CustomerContainer> RetrieveUserInfoAsync(WpfApplication2.SuperStoreServiceReference.AuthenticationCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuperStoreServiceInterface/RetrieveAvailableProducts", ReplyAction="http://tempuri.org/SuperStoreServiceInterface/RetrieveAvailableProductsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/SuperStoreServiceInterface/RetrieveAvailableProductsFaultExcep" +
            "tionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        WpfApplication2.SuperStoreServiceReference.ProductResponseContainer[] RetrieveAvailableProducts(WpfApplication2.SuperStoreServiceReference.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuperStoreServiceInterface/RetrieveAvailableProducts", ReplyAction="http://tempuri.org/SuperStoreServiceInterface/RetrieveAvailableProductsResponse")]
        System.Threading.Tasks.Task<WpfApplication2.SuperStoreServiceReference.ProductResponseContainer[]> RetrieveAvailableProductsAsync(WpfApplication2.SuperStoreServiceReference.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuperStoreServiceInterface/RetrievePurchaseHistory", ReplyAction="http://tempuri.org/SuperStoreServiceInterface/RetrievePurchaseHistoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/SuperStoreServiceInterface/RetrievePurchaseHistoryFaultExcepti" +
            "onFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        WpfApplication2.SuperStoreServiceReference.PurchaseResponseContainer[] RetrievePurchaseHistory(WpfApplication2.SuperStoreServiceReference.AuthenticationCredentials credentials, WpfApplication2.SuperStoreServiceReference.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuperStoreServiceInterface/RetrievePurchaseHistory", ReplyAction="http://tempuri.org/SuperStoreServiceInterface/RetrievePurchaseHistoryResponse")]
        System.Threading.Tasks.Task<WpfApplication2.SuperStoreServiceReference.PurchaseResponseContainer[]> RetrievePurchaseHistoryAsync(WpfApplication2.SuperStoreServiceReference.AuthenticationCredentials credentials, WpfApplication2.SuperStoreServiceReference.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuperStoreServiceInterface/PurchaseProduct", ReplyAction="http://tempuri.org/SuperStoreServiceInterface/PurchaseProductResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/SuperStoreServiceInterface/PurchaseProductFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        WpfApplication2.SuperStoreServiceReference.PurchaseResponseContainer PurchaseProduct(WpfApplication2.SuperStoreServiceReference.AuthenticationCredentials credentials, WpfApplication2.SuperStoreServiceReference.PurchaseRequestContainer productToBuy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuperStoreServiceInterface/PurchaseProduct", ReplyAction="http://tempuri.org/SuperStoreServiceInterface/PurchaseProductResponse")]
        System.Threading.Tasks.Task<WpfApplication2.SuperStoreServiceReference.PurchaseResponseContainer> PurchaseProductAsync(WpfApplication2.SuperStoreServiceReference.AuthenticationCredentials credentials, WpfApplication2.SuperStoreServiceReference.PurchaseRequestContainer productToBuy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuperStoreServiceInterface/AddProduct", ReplyAction="http://tempuri.org/SuperStoreServiceInterface/AddProductResponse")]
        void AddProduct(WpfApplication2.SuperStoreServiceReference.ProductResponseContainer product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuperStoreServiceInterface/AddProduct", ReplyAction="http://tempuri.org/SuperStoreServiceInterface/AddProductResponse")]
        System.Threading.Tasks.Task AddProductAsync(WpfApplication2.SuperStoreServiceReference.ProductResponseContainer product);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SuperStoreServiceInterfaceChannel : WpfApplication2.SuperStoreServiceReference.SuperStoreServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SuperStoreServiceInterfaceClient : System.ServiceModel.ClientBase<WpfApplication2.SuperStoreServiceReference.SuperStoreServiceInterface>, WpfApplication2.SuperStoreServiceReference.SuperStoreServiceInterface {
        
        public SuperStoreServiceInterfaceClient() {
        }
        
        public SuperStoreServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SuperStoreServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuperStoreServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuperStoreServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WpfApplication2.SuperStoreServiceReference.AuthenticationCredentials RegisterNewUser(WpfApplication2.SuperStoreServiceReference.RegistrationContainer userDetails) {
            return base.Channel.RegisterNewUser(userDetails);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.SuperStoreServiceReference.AuthenticationCredentials> RegisterNewUserAsync(WpfApplication2.SuperStoreServiceReference.RegistrationContainer userDetails) {
            return base.Channel.RegisterNewUserAsync(userDetails);
        }
        
        public WpfApplication2.SuperStoreServiceReference.CustomerContainer RetrieveUserInfo(WpfApplication2.SuperStoreServiceReference.AuthenticationCredentials credentials) {
            return base.Channel.RetrieveUserInfo(credentials);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.SuperStoreServiceReference.CustomerContainer> RetrieveUserInfoAsync(WpfApplication2.SuperStoreServiceReference.AuthenticationCredentials credentials) {
            return base.Channel.RetrieveUserInfoAsync(credentials);
        }
        
        public WpfApplication2.SuperStoreServiceReference.ProductResponseContainer[] RetrieveAvailableProducts(WpfApplication2.SuperStoreServiceReference.Pagination pagination) {
            return base.Channel.RetrieveAvailableProducts(pagination);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.SuperStoreServiceReference.ProductResponseContainer[]> RetrieveAvailableProductsAsync(WpfApplication2.SuperStoreServiceReference.Pagination pagination) {
            return base.Channel.RetrieveAvailableProductsAsync(pagination);
        }
        
        public WpfApplication2.SuperStoreServiceReference.PurchaseResponseContainer[] RetrievePurchaseHistory(WpfApplication2.SuperStoreServiceReference.AuthenticationCredentials credentials, WpfApplication2.SuperStoreServiceReference.Pagination pagination) {
            return base.Channel.RetrievePurchaseHistory(credentials, pagination);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.SuperStoreServiceReference.PurchaseResponseContainer[]> RetrievePurchaseHistoryAsync(WpfApplication2.SuperStoreServiceReference.AuthenticationCredentials credentials, WpfApplication2.SuperStoreServiceReference.Pagination pagination) {
            return base.Channel.RetrievePurchaseHistoryAsync(credentials, pagination);
        }
        
        public WpfApplication2.SuperStoreServiceReference.PurchaseResponseContainer PurchaseProduct(WpfApplication2.SuperStoreServiceReference.AuthenticationCredentials credentials, WpfApplication2.SuperStoreServiceReference.PurchaseRequestContainer productToBuy) {
            return base.Channel.PurchaseProduct(credentials, productToBuy);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.SuperStoreServiceReference.PurchaseResponseContainer> PurchaseProductAsync(WpfApplication2.SuperStoreServiceReference.AuthenticationCredentials credentials, WpfApplication2.SuperStoreServiceReference.PurchaseRequestContainer productToBuy) {
            return base.Channel.PurchaseProductAsync(credentials, productToBuy);
        }
        
        public void AddProduct(WpfApplication2.SuperStoreServiceReference.ProductResponseContainer product) {
            base.Channel.AddProduct(product);
        }
        
        public System.Threading.Tasks.Task AddProductAsync(WpfApplication2.SuperStoreServiceReference.ProductResponseContainer product) {
            return base.Channel.AddProductAsync(product);
        }
    }
}
