//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperStoreLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int id { get; set; }
        public int amount { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Product product { get; set; }
        public virtual Customer customer { get; set; }
    }
}
